bcgov/orgbook-configurations

- openshift/templates/frontend/frontend-build.json
- openshift/templates/frontend/frontend-deploy.json
- openshift/templates/frontend/frontend-runtime-build.json
- to support refactoring done within the indy-catalyst repository.
> Update build configurations

- openshift/templates/agent/agent-deploy.overrides.sh
- openshift/templates/agent/agent-deploy.yaml
- Also made logging level configurable.
- resolves #19
> Make agent admin mode configurable

- openshift/templates/agent/agent-deploy.yaml
- Add support for specifying any url.
> Fix genesis url

- openshift/manage
- openshift/templates/agent/agent-deploy.yaml
- openshift/templates/api/api-deploy.json
> Add getDbDiskUsage command to manage script.

- src/bc/baseConfig.groovy
> Change package name to match namespace change.

- openshift/templates/backup/backup-deploy.bc.dev.param
- openshift/templates/backup/backup-deploy.bc.param
- openshift/templates/backup/backup-deploy.json
- openshift/templates/backup/config/backup.conf
> Update backup configurations

- openshift/templates/agent/agent-deploy.bc.dev.param
- openshift/templates/agent/agent-deploy.bc.param
- openshift/templates/agent/agent-deploy.bc.test.param
> Refine deployment configuration

- openshift/manage
> Automate environment 'reset' process.

- openshift/manage
> Update manage script usage documentation.

- openshift/templates/agent/agent-deploy.yaml
> Fix agent startup issues

- openshift/templates/agent/agent-deploy.bc.prod.param
- openshift/templates/api/api-deploy.bc.prod.param
- openshift/templates/backup/backup-deploy.bc.prod.param
- openshift/templates/db/db-deploy.bc.prod.param
- openshift/templates/frontend/frontend-deploy.bc.prod.param
- openshift/templates/msg-queue-worker/msg-queue-worker-deploy.bc.prod.param
- openshift/templates/msg-queue/msg-queue-deploy.bc.prod.param
- openshift/templates/schema-spy/schema-spy-deploy.bc.prod.param
- openshift/templates/search-engine/search-engine-deploy.bc.prod.param
- openshift/templates/wallet/wallet-deploy.bc.prod.param
> Add production deployment configurations

- jenkins/deployment/bc-prod/Jenkinsfile
- jenkins/deployment/bc-prod/Jenkinsfile.bc.pipeline.param
- jenkins/deployment/bc-prod/config.groovy
> Add `prod` deployment pipeline

- jenkins/deployment/bc-prod/Jenkinsfile.bc.pipeline.param
> Fix source repository reference

- jenkins/deployment/bc-prod/Jenkinsfile
> Fix pipeline name

- openshift/templates/agent/agent-deploy.bc.dev.param
- openshift/templates/agent/agent-deploy.bc.param
- openshift/templates/agent/agent-deploy.bc.prod.param
- openshift/templates/agent/agent-deploy.bc.test.param
- openshift/templates/agent/agent-deploy.yaml
> Add `agent-admin` routes

- jenkins/frontend/config.groovy
- aries-vcr frontend build was refactored to looks for all themes in the `./client/themes` directory.
> Update frontend build configuration

- openshift/templates/frontend/frontend-deploy.bc.dev.param
- openshift/templates/frontend/frontend-deploy.bc.param
- openshift/templates/frontend/frontend-deploy.bc.prod.param
- openshift/templates/frontend/frontend-deploy.bc.test.param
- openshift/templates/frontend/frontend-deploy.json
> Add API rate limit settings.

- .gitattributes
> Update git attributes

- openshift/templates/agent/agent-build.yaml
- openshift/templates/agent/agent-deploy.yaml
Changes have NOT been deployed
> Upgrade ACA-Py to 0.6.0

- openshift/templates/agent/agent-deploy.yaml
Signed-off-by: Emiliano Suñé <emiliano.sune@gmail.com>
> Updates for ACA-Py 0.6.0

- openshift/templates/db/db-deploy.yaml
> Fix for 'could not resize shared memory segment' issue.

- openshift/templates/api/api-deploy.bc.dev.param
- openshift/templates/api/api-deploy.bc.param
- openshift/templates/api/api-deploy.bc.prod.param
- openshift/templates/api/api-deploy.bc.test.param
- openshift/templates/api/api-deploy.yaml
> Add API_VERSION_ROUTING_MIDDLEWARE setting

- openshift/templates/api/api-deploy.bc.dev.param
- openshift/templates/api/api-deploy.bc.param
- openshift/templates/api/api-deploy.bc.prod.param
- openshift/templates/api/api-deploy.bc.test.param
- openshift/templates/api/api-deploy.yaml
> Add SP_TRACKING_EMITTER setting

- openshift/templates/api/api-build.yaml
updated aries-vcr api base image to target python3.9
Signed-off-by: wadeking98 <wkingnumber2@gmail.com>
> updated api base image

- openshift/templates/frontend/config/Caddyfile
- Use legacy proxy behavior for now.
> Add trusted_proxies settings to fix issues with swagger page

- sysdig/sysdig-team.yml
> Add raj to the sysdig team

- openshift/templates/wallet/wallet-deploy.yaml
- Allow the audit pod from the DTS monitoring namespace to access the wallet pod.
> Update the wallet's NSP

- openshift/templates/vc-service/vc-service-deploy.vc-service-bc.prod.param
- openshift/templates/vc-service/vc-service-deploy.vc-service-bc.test.param
Forgot to un-comment the custom values for `test` and `prod` in the previous PR... 😅
> Updated settings for vc-service

- .gitignore
- openshift/templates/agent/agent-deploy.yaml
- openshift/templates/api/api-deploy.yaml
- openshift/templates/backup/backup-deploy.overrides.sh
- openshift/templates/backup/backup-deploy.yaml
- openshift/templates/db/db-deploy.overrides.sh
- openshift/templates/db/db-deploy.yaml
- openshift/templates/frontend/frontend-deploy.overrides.sh
- openshift/templates/frontend/frontend-deploy.yaml
- openshift/templates/msg-queue-worker/msg-queue-worker-deploy.yaml
- openshift/templates/msg-queue/msg-queue-deploy.overrides.sh
- openshift/templates/msg-queue/msg-queue-deploy.yaml
- openshift/templates/offline-indexer/offline-indexer-deploy.yaml
- openshift/templates/schema-spy/schema-spy-deploy.overrides.sh
- openshift/templates/schema-spy/schema-spy-deploy.yaml
- openshift/templates/search-engine/search-engine-deploy.yaml
- openshift/templates/vc-service/vc-service-deploy.yaml
- openshift/templates/wallet/wallet-deploy.overrides.sh
- openshift/templates/wallet/wallet-deploy.yaml
Migrating deploymentconfig objects to Deployment manifests.
> Migrate DeploymentConfigs to Deployments
